name: homlp
channels:
  - conda-forge
  - nodefaults
dependencies:
  - accelerate>=1.5 # used in chapters 14-18 with the Transformers library
  - box2d-py>=2.3 # used in chapter 19, exercise 8
  - diffusers>=0.34 # used in chapter 18 for diffusion models
  - ffmpeg>=7.1 # used in the matplotlib tutorial to generate animations
  - google-genai>=1.20 # used in chapter 16 to access Gemini 2.5 Pro
  - graphviz>=12.0 # used in chapter 5 for dot files
  - gymnasium-atari>=1.0
  - ipython # a powerful Python shell
  - joblib>=1.4 # used in chapter 2 to save/load Scikit-Learn models
  - jupyter>=1.1 # to edit and run Jupyter notebooks
  - jupyterlab>=4.2 # a different UI for Jupyter notebooks
  - lion-pytorch>=0.2 # a powerful optimizer, introduced in chapter 11
  - matplotlib>=3.10 # beautiful plots. See tutorial tools_matplotlib.ipynb
  - nbdime>=4.0 # optional tool to diff Jupyter notebooks
  - nltk>=3.9 # optionally used in chapter 3, exercise 4
  - numexpr>=2.10 # used in the Pandas tutorial for numerical expressions
  - numpy>=1.26 # Powerful n-dimensional arrays and numerical computing tools
  - pandas>=2.2 # data analysis and manipulation tool
  - pillow>=11.1 # image manipulation library, (used by matplotlib.image.imread)
  - pip # Python's package-management system
  - py-xgboost>=2.1 # used in chapter 6 for optimized Gradient Boosting
  - pygame>=2.6 # used in chapter 19 for the LunarLander-v2 environment
  - python-graphviz>=0.20 # used in chapter 6 for dot files
  - python>=3.11 # your beloved programming language! :)
  - scikit-learn>=1.6 # machine learning library
  - scipy>=1.14 # scientific/technical computing library
  - statsmodels>=0.14 # used in chapter 13 for time series analysis
  - pytorch>=2.4 # deep learning library
  - sentence-transformers>=4.1 # Sentence embedding library by Hugging Face
  - sentencepiece>=0.2.0 # Tokenizer used in chapter 14
  - stable-baselines3>=2.7 # Reinforcement Learning library used in chapter 19
  - tensorboard>=2.18 # Visualization toolkit
  - torchvision>=0.19 # computer vision library
  - torchaudio
  - torchmetrics>=1.6 # PyTorch metrics library
  - transformers>=4.48 # NLP library and more by Hugging Face
  - trl>=0.17 # Transformers fine-tuning used in chapter 15
  - datasets>=3.2 # Hugging Face datasets
  - ultralytics>=8.3 # computer vision library used in chapter 12
  - wheel # built-package format for pip
  - widgetsnbextension>=4.0 # interactive HTML widgets for Jupyter notebooks
  - pip:
      - AutoROM
      - torch-tb-profiler #~=0.4.3 # profiling plugin for TensorBoard
      - urlextract #~=1.9.0 # optionally used in chapter 3, exercise 4
      - bitsandbytes #~=0.42.0
      - hf_xet #~=1.1.3
      - lap #~=0.5.12
